---
title: "Chapter 3 Excercises"
output: github_document
---

Code and solutions for Chapter 3 of the [Statistical Rethinking 2 Ed.](https://xcelab.net/rm/statistical-rethinking/) textbook by R. McElreath.

```{r load-packages}
library(rethinking)
library(tidyverse)
library(ggthemes)
```

Set the palette and the running theme for ggplot2.

```{r set-theme-palette}
theme_set(theme_bw())
theme_update(axis.text.x = element_text(
angle = -45,
hjust = 0,
vjust = 0.5
))
```

## Easy

```{r}
p_grid <- seq(from = 0, to = 1, length.out = 1000)
prior <- rep(1, 1000)
likelihood <- dbinom(6, size = 9, prob = p_grid)
posterior <- prior * likelihood
posterior <- posterior / sum(posterior)
```

```{r}
tosses <- tibble(p_grid = seq(0, 1, length.out = 1000),
                 prior = rep(1, 1000),
                 likelihood = dbinom(6, size = 9, prob = p_grid)) %>%
  mutate(posterior = prior * likelihood) %>%
  mutate(posterior = posterior /sum(posterior))

glimpse(tosses)
```

```{r}
tosses %>%
  ggplot(aes(x = p_grid, y = prior)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Prior Distribution") 
```

```{r}
tosses %>%
  ggplot(aes(x = p_grid, y = likelihood)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Likelihood Distribution") 
```

```{r}
tosses %>%
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Posterior Distribution") 
```

```{r}
set.seed(100)

n_samples <- 1e4

p_samples <- tosses %>%
  slice_sample(n = n_samples,
               weight_by = posterior,
               replace = T)

glimpse(p_samples)
```

```{r}
p_samples %>%
  ggplot(aes(p_grid)) +
  geom_density() +
  labs(x = "p Water",
       title = "Posterior Samples Distribution")
```

### 3E1

```{r}
p_samples %>%
  summarise(p_less_point2 = mean(p_grid < 0.2))
```

### 3E2

```{r}
p_samples %>%
  summarise(p_less_point8 = mean(p_grid < 0.8))
```

### 3E3

```{r}
p_samples %>%
  summarise(p_between_point2_point_8 = mean(p_grid > 0.2 & p_grid < 0.8))
```

### 3E4

```{r}
p_samples %>%
  summarise(p_20_below = quantile(p_grid, 0.2))
```

### 3E5

```{r}
p_samples %>%
  summarise(p_20_above = quantile(p_grid, 0.8))
```

### 3E6

```{r}
p_samples %>%
  summarise(p_hdpi_66 = HPDI(p_grid, 0.66))
```

## Medium

### 3M1

```{r}
tosses_2 <- tibble(p_grid = seq(0, 1, length.out = 1000),
                 prior = rep(1, 1000),
                 likelihood = dbinom(8, size = 15, prob = p_grid)) %>%
  mutate(posterior = prior * likelihood) %>%
  mutate(posterior = posterior /sum(posterior))

glimpse(tosses_2)
```

```{r}
tosses_2 %>%
  ggplot(aes(x = p_grid, y = likelihood)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Likelihood Distribution 2") 
```

```{r}
tosses_2 %>%
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Posterior Distribution 2") 
```

### 3M2

```{r}
p_samples_2 <- tosses_2 %>%
  slice_sample(n = n_samples,
               weight_by = posterior,
               replace = T)

glimpse(p_samples_2)
```

```{r}
p_samples_2 %>%
  summarise(p_hdpi_90 = HPDI(p_grid, 0.9))
```

### 3M3

```{r}
p_samples_2 <- p_samples_2 %>%
  mutate(n_water_15 = rbinom(n_samples, 15, p_grid))

glimpse(p_samples_2)
```

```{r}
p_samples_2 %>%
  summarise(p_water_8 = mean(n_water_15 == 8))
```

### 3M4

```{r}
p_samples_2 %>%
  mutate(n_water_9 = rbinom(n_samples, 9, p_grid)) %>%
  summarise(p_water_6 = mean(n_water_9 == 6))
```

# \#\# 3M5

```{r}
tosses_3 <- tibble(p_grid = seq(0, 1, length.out = 1000),
                   prior = ifelse(p_grid < 0.5, 0, 1),
                   likelihood = dbinom(6, size = 9, prob = p_grid)) %>%
  mutate(posterior = prior * likelihood) %>%
  mutate(posterior = posterior /sum(posterior))

glimpse(tosses_3)
```

```{r}
tosses_3 %>%
  ggplot(aes(x = p_grid, y = prior)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Prior Distribution") 
```

```{r}
tosses_3 %>%
  ggplot(aes(x = p_grid, y = likelihood)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Likelihood Distribution") 
```

```{r}
tosses_3 %>%
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Posterior Distribution") 
```

```{r}
set.seed(100)

p_samples_3 <- tosses_3 %>%
  slice_sample(n = n_samples,
               weight_by = posterior,
               replace = T)

glimpse(p_samples_3)
```

```{r}
p_samples_3 %>%
  ggplot(aes(p_grid)) +
  geom_density() +
  scale_x_continuous(lim = c(0,1)) +
  labs(x = "p Water",
       title = "Posterior Samples Distribution")
```

### 3E1-bis

```{r}
p_samples_3 %>%
  summarise(p_less_point2 = mean(p_grid < 0.2))
```

### 3E2-bis

```{r}
p_samples_3 %>%
  summarise(p_less_point8 = mean(p_grid < 0.8))
```

### 3E3-bis

```{r}
p_samples_3 %>%
  summarise(p_between_point2_point_8 = mean(p_grid > 0.2 & p_grid < 0.8))
```

### 3E4-bis

```{r}
p_samples_3 %>%
  summarise(p_20_below = quantile(p_grid, 0.2))
```

### 3E5-bis

```{r}
p_samples_3 %>%
  summarise(p_20_above = quantile(p_grid, 0.8))
```

### 3E6-bis

```{r}
p_samples_3 %>%
  summarise(p_hdpi_66 = HPDI(p_grid, 0.66))
```

### 3M1 - bis

```{r}
tosses_4 <- tibble(p_grid = seq(0, 1, length.out = 1000),
                   prior = ifelse(p_grid < 0.5, 0, 1),
                   likelihood = dbinom(8, size = 15, prob = p_grid)) %>%
  mutate(posterior = prior * likelihood) %>%
  mutate(posterior = posterior /sum(posterior))

glimpse(tosses_4)
```

```{r}
tosses_4 %>%
  ggplot(aes(x = p_grid, y = likelihood)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Likelihood Distribution 2") 
```

```{r}
tosses_4 %>%
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line() +
  labs(x = "p Water",
       y = "Density",
       title = "Posterior Distribution 2") 
```

### 3M2 - bis

```{r}
p_samples_4 <- tosses_4 %>%
  slice_sample(n = n_samples,
               weight_by = posterior,
               replace = T)

glimpse(p_samples_4)
```

```{r}
p_samples_4 %>%
  summarise(p_hdpi_90 = HPDI(p_grid, 0.9))
```

### 3M3 - bis

```{r}
p_samples_4 <- p_samples_4 %>%
  mutate(n_water_15 = rbinom(n_samples, 15, p_grid))

glimpse(p_samples_4)
```

```{r}
p_samples_4 %>%
  summarise(p_water_8 = mean(n_water_15 == 8))
```

### 3M4 - bis

```{r}
p_samples_4 %>%
  mutate(n_water_9 = rbinom(n_samples, 9, p_grid)) %>%
  summarise(p_water_6 = mean(n_water_9 == 6))
```

## Hard

```{r}
data(homeworkch3)

birth_data <- tibble(first = birth1,
                 second = birth2) 
birth_data %>%
  summarize(across(first:second, list(sum = sum)))
```

### 3H1

```{r}
births <- tibble(
  p_grid = seq(from = 0, to = 1, length.out = 1000),
  prior = rep(1, 1000),
  likelihood = dbinom(x = 111, size = 200, prob = p_grid)
) %>%
  mutate(posterior = prior*likelihood) %>%
  mutate(posterior = posterior/sum(posterior))

glimpse(births)
```

```{r}
births %>%
  ggplot(aes(x = p_grid, y = prior)) +
  geom_line() +
  labs(x = "p Male",
       y = "Density",
       title = "Prior Distribution") 
```

```{r}
births %>%
  ggplot(aes(x = p_grid, y = likelihood)) +
  geom_line() +
  labs(x = "p Male",
       y = "Density",
       title = "Likelihood Distribution") 
```

```{r}
births %>%
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line() +
  labs(x = "p Male",
       y = "Density",
       title = "Posterior Distribution") 
```

```{r}
births %>%
  slice(which.max(posterior))
```

### 3H2

```{r}
set.seed(100)

birth_samples <- births %>%
  slice_sample(n = n_samples, 
               weight_by = posterior,
               replace = TRUE)

glimpse(birth_samples)
```

```{r}
birth_samples %>%
  summarize(HPDI_50 = HPDI(p_grid, 0.50),
            HPDI_89 = HPDI(p_grid, 0.89),
            HPDI_97 = HPDI(p_grid, 0.97))
```

### 3H3

```{r}
birth_samples_200 <- birth_samples %>%
  mutate(n_male = rbinom(n_samples, 200, p_grid))

glimpse(birth_samples_200)
```

```{r}
birth_samples_200 %>%
  ggplot(aes(n_male)) +
  geom_histogram(binwidth = 2,
                 fill = "black",
                 color = "white")
```

### 3H4

```{r}
birth_samples_100 <- birth_samples %>%
  mutate(n_male = rbinom(n_samples, 100, p_grid))

glimpse(birth_samples_100)
```

```{r}
birth_samples_100 %>%
  ggplot(aes(n_male)) +
  geom_histogram(binwidth = 2,
                 fill = "black",
                 color = "white")
```

### 3H5

```{r}
birth_data %>%
  filter(first == 0) %>%
  summarise(n_tot = n(),
            n_girls_boys = sum(second))
```

```{r}
birth_samples_g_b <- birth_samples %>%
  mutate(n_male = rbinom(n_samples, 49, p_grid))

glimpse(birth_samples_100)
```

```{r}
birth_samples_g_b %>%
  ggplot(aes(n_male)) +
  geom_histogram(binwidth = 2,
                 fill = "black",
                 color = "white")
```

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
