---
title: "Chapter4"
output: html_document
---

```{r 4.7}
library(rethinking)
data(Howell1)
d <- Howell1
```
```{r 4.8}
str(d)
```

```{r 4.9}
precis(d)
```
```{r 4.10}
d$height
```

```{r 4.11}
d2 <- d[d$age >= 18,]
```

```{r 4.12}
curve(dnorm(x, 178, 20), from = 100, to = 250)
```
```{r 4.13}
curve(dunif(x, 0, 50), from = -10, to = 60)
```
```{r 4.14}
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```
```{r 4.15}
sample_mu <- rnorm(1e4, 178, 100)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```
```{r 4.16}
mu.list <- seq(from = 150, to = 160, length.out = 100)
sigma.list <- seq(from = 7, to = 9, length.out = 100)
post <- expand.grid(mu = mu.list, sigma = sigma.list)

post$LL <- sapply(1:nrow(post), function(i) sum(dnorm(d2$height, post$mu[i], post$sigma[i]), log = TRUE))

post$prod <- post$LL + dnorm(post$mu, 178, 20, TRUE) + dunif(post$sigma, 0, 50, TRUE)

post$prob <- exp(post$prod - max(post$prod))
```

```{r 4.17}
contour_xyz(post$mu, post$sigma, post$prob)
```
```{r 4.18}
image_xyz(post$mu, post$sigma, post$prob)
```

```{r 4.19}
sample.rows <- sample(1:nrow(post), 
                      size = 1e4, 
                      replace = TRUE,
                      prob = post$prob)

sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]
```

```{r 4.20}
plot(sample.mu, 
     sample.sigma, 
     cex = 0.5,
     pch = 16,
     col = col.alpha(rangi2, 0.1))
```
```{r 4.21}
dens(sample.mu)
dens(sample.sigma)
```
```{r 4.22}
PI(sample.mu)
PI(sample.sigma)
```

```{r 4.27}
flist <- alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(178, 20),
  sigma ~ dunif(0, 50)
)
```

```{r 4.28}
m4.1 <- quap(flist, data = d2)
```

```{r 4.29}
precis(m4.1)
```
```{r 4.31}
m4.2 <- quap(alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(178, 0.1),
  sigma ~ dunif(0, 50)
), data = d2)

precis(m4.2)
```
```{r 4.32}
vcov(m4.1)
```
```{r 4.33}
diag(vcov(m4.1))
cov2cor(vcov(m4.1))
```
```{r 4.34}
post <- extract.samples(m4.1, n = 1e4)
head(post)
```
```{r}
precis(post)
```

```{r 4.37}
plot(d2$height ~ d2$weight)
```
```{r 4.38}
set.seed(2971)
N <- 100
a <- rnorm(N, 178, 20)
b <- rnorm(N, 0, 10)
```

```{r 4.39}
plot(NULL, xlim = range(d2$weight), ylim = c(-100, 400), xlab = "weight", ylab = "height")
abline(h = 0, lty = 2)
abline(h = 272, lty = 1, lwd = 0.5)
mtext("b ~ dnorm(0,10)")
xbar <- mean(d2$weight)
for(i in 1:N){
  curve(a[i] + b[i]*(x - xbar),
        from = min(d2$weight),
        to = max(d2$weight),
        add = TRUE,
        col = col.alpha("black", 0.2))
}
```
```{r 4.40}
b <- rlnorm(1e4, 0, 1)
dens(b, xlim = c(0,5), adj = 0.1)
```
```{r 4.41}
set.seed(2971)
N <- 100
a <- rnorm(N, 178, 20)
b <- rlnorm(N, 0, 1)

plot(NULL, xlim = range(d2$weight), ylim = c(-100, 400), xlab = "weight", ylab = "height")
abline(h = 0, lty = 2)
abline(h = 272, lty = 1, lwd = 0.5)
mtext("b ~ dnorm(0,10)")
xbar <- mean(d2$weight)
for(i in 1:N){
  curve(a[i] + b[i]*(x - xbar),
        from = min(d2$weight),
        to = max(d2$weight),
        add = TRUE,
        col = col.alpha("black", 0.2))
}
```
```{r 4.42}
m4.3 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b*(weight - xbar),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1),
    sigma ~ dunif(0,50)
  ),
  data = d2
)
```
```{r 4.44}
precis(m4.3)
```
```{r 4.45}
round(vcov(m4.3), 3)
```
```{r 4.46}
plot(height ~ weight, data = d2, col = rangi2)
post <- extract.samples(m4.3, n = 1e4)
a_map <- mean(post$a)
b_map <- mean(post$b)
curve(a_map + b_map*(x - xbar), add = TRUE)
```
```{r 4.47}
head(post, 5)
```

```{r 4.50}
mu_at_50 <- post$a + post$b*(50-xbar)
str(mu_at_50)
```
```{r 4.51}
dens(mu_at_50, col = rangi2, lwd = 2, xlab = "mu|weight=50")
```
```{r 4.52}
PI(mu_at_50, prob = 0.89)
```

```{r 4.53}
mu <- link(m4.3)
str(mu)
```

```{r 4.54}
weight.seq <- 25:70

mu <- link(m4.3, data = data.frame(weight = weight.seq))
str(mu)
```
```{r 4.55}
plot(height ~ weight, data = d2, type = "n")

for(i in 1:100){
  points(weight.seq, 
         mu[i,], 
         pch = 16,
         col = col.alpha(rangi2, 0.1))
}
```
```{r 4.56}
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob = 0.89)
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.89)
```
```{r 4.57}
plot(height ~ weight, data = d2, col = rangi2)
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
```
```{r 4.59}
sim.height <- sim(m4.3, data = list(weight = weight.seq))
str(sim.height)
```
```{r 4.61}
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
plot(height ~ weight, data = d2, col = rangi2)
lines(weight.seq, mu.mean)
shade(mu.HPDI, weight.seq)
shade(height.PI, weight.seq)
```
```{r 4.65}
d$weight_s <- (d$weight - mean(d$weight))/sd(d$weight)
d$weight_s2 <- d$weight_s^2

m4.5 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1*weight_s + b2*weight_s2,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 1),
    sigma ~ dunif(0,50)
  ), data = d
)
```

```{r 4.66}
precis(m4.5)
```
```{r 4.67}
weight.seq <- seq(-2.2, 2, length.out = 30)
pred_dat <- list(weight_s = weight.seq, weight_s2 = weight.seq^2)
mu <- link(m4.5, data = pred_dat)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob = 0.89)
sim.height <- sim(m4.5, data = pred_dat)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
```

```{r 4.68}
plot(height ~ weight_s, data = d, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```
```{r 4.69}
d$weight_s3 <- d$weight_s^3

m4.6 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1*weight_s + b2*weight_s2 + b3*weight_s3,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0,1),
    b2 ~ dnorm(0,10),
    b3 ~ dnorm(0, 10),
    sigma ~ dunif(0,50)
  ), data = d
)
```

```{r}
precis(m4.6)
```
```{r}
weight.seq <- seq(-2.2, 2, length.out = 30)
pred_dat <- list(weight_s = weight.seq, 
                 weight_s2 = weight.seq^2, 
                 weight_s3 = weight.seq^3)
mu <- link(m4.6, data = pred_dat)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob = 0.89)
sim.height <- sim(m4.6, data = pred_dat)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
```

```{r}
plot(height ~ weight_s, data = d, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```
```{r 4.72}
data("cherry_blossoms")
d <- cherry_blossoms
precis(d)
```

```{r 4.73}
d2 <- d[complete.cases(d$doy),]
num_knots <- 15
knot_list <- quantile(d2$year, 
                      probs = seq(0, 1, length.out = num_knots))
```
```{r 4.74}
library(splines)
B <- bs(d2$year,
        knots = knot_list[-c(1, num_knots)],
        degree = 3,
        intercept = TRUE)

str(B)
```
```{r 4.75}
plot(NULL, 
     xlim = range(d2$year), 
     ylim = c(0,1), 
     xlab = "year", 
     ylab = "basis")

for(i in 1:ncol(B)) {
  lines(d2$year, B[,i])
}
```
```{r 4.76}
m4.7 <- quap(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + B %*% w,
    a ~ dnorm(100, 10),
    w ~ dnorm(0,10),
    sigma ~ dexp(1)
  ), 
  data = list(D = d2$doy, B = B),
  start = list(w = rep(0, ncol(B)))
)
```
```{r 4.77}
post <- extract.samples(m4.7)
precis(post, depth = 2)
```
```{r 4.77b}
str(post)
```


```{r 4.77c}
w <- apply(post$w, 2, mean)
plot(NULL, xlim = range(d2$year), ylim = c(-6,6),
     xlab = "year", ylab = "basis * weight")
for(i in 1:ncol(B)){
  lines(d2$year, w[i]*B[,i])
}
```
```{r 4.78}
mu <- link(m4.7)
mu_PI <- apply(mu, 2, PI, 0.97)

plot(d2$year, 
     d2$doy, 
     col = col.alpha(rangi2, 0.3),
     pch = 16)
shade(mu_PI, 
      d2$year,
      col = col.alpha("black", 0.5))
```











