---
title: "Chapter7"
output: html_document
---

```{r}
library(rethinking)
library(tidyverse)
```


```{r 7.1}
sppnames <- c("afarensis", "africanus", "habilis",
              "boisei", "rudolfensis", "ergaster", "sapiens")

brainvolcc <- c(438, 452, 612, 521, 752, 871, 1350)

masskg <- c(37.0, 35.5, 34.5, 41.5, 55.5, 61.0, 53.5)

d <- data.frame(species = sppnames,
                brain = brainvolcc,
                mass = masskg)
```

```{r fig7.2}
ggplot(d, aes(x = mass, y = brain, label = species)) +
         geom_point() +
  geom_text(nudge_x = 2,
            nudge_y = 1) +
  theme_bw() +
  xlab("body mass (kg)") +
  ylab("brain volume (cc)")
```
```{r 7.2}
d$mass_std <- (d$mass - mean(d$mass))/sd(d$mass)
d$brain_std <- d$brain/max(d$brain)
```

```{r 7.3}
m7.1 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b * mass_std,
    a ~ dnorm(0, 0.5),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1) # to make the sigma > 0
  ), data = d
)

precis(m7.1)
```
```{r 7.5}
set.seed(12)
s <- sim(m7.1)
r <- apply(s, 2, mean) - d$brain_std
resid_var <- var2(r)
outcome_var <- var2(d$brain_std)

1 - resid_var/outcome_var
```
```{r 7.6}
R2_is_bad <- function(quap_fit) {
  s <- sim(quap_fit, refresh = 0)
  r <- apply(s, 2, mean) - d$brain_std
  resid_var <- var2(r)
  outcome_var <- var2(d$brain_std)
  
  1 - resid_var/outcome_var
}
```

```{r 7.7}
m7.2 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std + b[2] * mass_std^2 , 
    a ~ dnorm(0, 0.5),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), 
  data = d,
  start = list(b=rep(0, 2)) # this is to specify b as a vector
  
)
```

```{r 7.8}
m7.3 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std + b[2] * mass_std^2 + 
      b[3] * mass_std^3 , 
    a ~ dnorm(0, 0.5),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), 
  data = d,
  start = list(b=rep(0, 3))
  
)

m7.4 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std + b[2] * mass_std^2 + 
      b[3] * mass_std^3 + b[4] * mass_std^4, 
    a ~ dnorm(0, 0.5),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), 
  data = d,
  start = list(b=rep(0, 4))
  
)

m7.5 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std + b[2] * mass_std^2 + 
      b[3] * mass_std^3 + b[4] * mass_std^4 +
      b[5] * mass_std^5,
    a ~ dnorm(0, 0.5),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), 
  data = d,
  start = list(b=rep(0, 5))
  
)

m7.6 <- quap(
  alist(
    brain_std ~ dnorm(mu, 0.001),
    mu <- a + b[1] * mass_std + b[2] * mass_std^2 + 
      b[3] * mass_std^3 + b[4] * mass_std^4 +
      b[5] * mass_std^5 + b[6] * mass_std^6,
    a ~ dnorm(0, 0.5),
    b ~ dnorm(0, 10)
  ), 
  data = d,
  start = list(b=rep(0, 6))
)
```

```{r 7.10}
plot_fit <- function(quap_fit) {
  mass_seq <- seq(min(d$mass_std), max(d$mass_std), length.out = 100)
  l <- link(quap_fit, data = list(mass_std = mass_seq))
  mu <- apply(l, 2, mean)
  ci <- apply(l, 2, PI)
  plot(brain_std ~ mass_std, data = d, ylim = c(0,1.2))
  lines(mass_seq, mu)
  shade(ci, mass_seq) 
}

brain_plot(m7.1)
```

```{r 7.10b}
brain_plot(m7.2)
```
```{r 7.10c}
brain_plot(m7.3)
```
```{r 7.10d}
brain_plot(m7.4)
```
```{r 7.10e}
brain_plot(m7.5)
```
```{r 7.10e}
brain_plot(m7.6)
```
```{r fig7.4a}
brain_loo_plot(m7.1)
```

```{r fig7.4b}
brain_loo_plot(m7.4)
```
```{r 7.13}
set.seed(1)
lppd(m7.1, n=1e4)
```
```{r 7.14}
set.seed(1)

log_prob <- sim(m7.1, ll = TRUE, n = 1e4)
n <- ncol(log_prob)
ns <- nrow(log_prob)

f <- function(i) log_sum_exp(log_prob[,i]) - log(ns)
```

```{r}
set.seed(1)
sapply(list(m7.1, m7.2, m7.3, m7.4, m7.5, m7.6), function(m) sum(lppd(m)))
```




